apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    create table user
    (
        id  uuid primary key not null,
        first_name varchar(50),
        last_name  varchar(50)
    );