apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-homework-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-homework
  template:
    metadata:
      labels:
        app: helm-homework
    spec:
      containers:
        - image: imalouhov/helm-homework:0.0.1
          name: homework-pod
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://172.24.0.242:32594/users"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: password