apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-homework-configmap
  labels:
    app: postgres
data:
  database_url: localhost
  database_name: homework-db
  database_user: admin
  password: admin