apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-homework-ingress
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helm-homework-service
                port:
                  number: 80