apiVersion: v1
kind: Service
metadata:
  name: helm-homework-service
  labels:
    app: helm-homework-svc
spec:
  type: LoadBalancer
  selector:
    app: helm-homework
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080